### PR TITLE
Minor update to depth- and time-dependent unit testing

### PR DESCRIPTION
**Pull request by michaeldenes**
There was an issue with the unit testing, caused by a recent update to parcels. The testing data uses only 5 levels, down to 4.7m depth. Particles would cause an out of bounds error in such a case, and be deleted. Updating the density of the particles lets them still sink, but not as quickly as before.

### CODE REVIEW

**Comment by michaeldenes** [comment]
Additionally, there was some missing wind data (updated in 2e48261, which includes a few more days of data) causing a time-interpolation error. I'm not sure how these passed in the past, unless time_extrapolation was set to true by default, and no longer?

**Comment by erikvansebille** [comment]
> Additionally, there was some missing wind data (updated in [2e48261](https://github.com/OceanParcels/plasticparcels/commit/2e482614666df76e3ca9927f1396b48757743d0d), which includes a few more days of data) causing a time-interpolation error. I'm not sure how these passed in the past, unless time_extrapolation was set to true by default, and no longer?

The change we made in v3.0.5 that could have impacted this is that the `particle.state` is the maximum of _any_ statuscode returned by the Field interpolations during an iteration, whereas before v3.0.5 it was the _latest_ statuscode. So if in your list of Kernels the last Field interpolation returned a SUCCESS, then previous errors were not stored on the `particle.state`. See [#1645](https://github.com/OceanParcels/Parcels/pull/1645) for the details of this change

**Comment by michaeldenes** [comment]
@erikvansebille, this makes a lot of sense, and why I didn't pickup any of these data related issues earlier! Thanks for linking this!

**Comment by michaeldenes** [comment]
@VeckoTheGecko would you mind helping me look at why the readthedocs build fails?

**Comment by VeckoTheGecko** [comment]
Its to do with Python 3.13. I'll put up a PR

**Comment by michaeldenes** [comment]
Thank you! Glad I asked, I wouldn't have picked up on that!

**Comment by VeckoTheGecko** [comment]
Done. Can you check the site is as you expect once its rendered?

**Comment by michaeldenes** [comment]
@VeckoTheGecko  looks good, thanks mate!

**Pull request merged**
